research_task:
  description: >
    针对用户指定的主题进行深入调研。
    请确保你找到所有有价值、有趣且相关的最新信息。
    
  expected_output: >
    返回一个包含 10 条要点的列表，总结该主题下最重要、最相关的内容。
  agent: researcher

reporting_task:
  description: >
    请根据上下文中的研究内容，撰写完整的 markdown 报告，包含每个主题的说明部分
    最后，请调用 FileWriterTool 工具并将报告保存为 .md 文件。返回JSON格式的文件信息
  expected_output: >
   {
      "content": "内容",
      "filename": "output/xxx.md",
      "summary": "总结"
    }
    - content: 为生成的文件
    - filename: 输出保存的路径
    - summary: 对内容进行简要说明

  agent: reporting_analyst

distribute_task:
  description: >
    根据用户输入的 {user_input}，结合提供的 {agents} 和 {tasks} 信息，
    选择最合适的智能体（agents）和任务（tasks）进行分配。
  expected_output: >
    返回一个 distribution_config 字典，其中包含选中的智能体和任务。
    这些智能体和任务应来自输入的 agents_dict 和 tasks_dict。

    返回格式应如下：
    {
      "distribution_config": {
        "agents": [<agent_object>, ...],
        "tasks": [<task_object>, ...]
      }
    }
    每个 <agent_object> 和 <task_object> 都应是传入的 {agents}  或 {tasks} 字典中的对应项。
  agent: planner

code_task:
  description: >
    "根据用户请求：\n\n"
        "{user_input}\n\n"
        "你需要：\n"
        "- 生成可运行的 Python 代码来满足需求\n"
        "- 使用 FileWriterTool 写入 `.py` 文件（必须）保存到 output/ 文件夹下\n"
        "- 执行代码并输出结果（如有）\n"
        "- 最终以 JSON 格式返回：包含 'content', 'filename', 'summary' 字段。\n"
        "注意：请务必使用工具写文件，而不是仅打印。"
  expected_output: >
   {
      "content": "内容",
      "filename": "output/xxx.py",
      "summary": "总结"
    }
    - content: 为生成的文件
    - filename: 输出保存的路径
    - summary: 对内容进行简要说明
  agent: programmer


education_task:
  description: >
    请根据用户的问题 {user_input} 进行清晰、系统的讲解。
    如有需要，可提供 Python 代码示例或输出文件。
  expected_output: >
    输出关于 {user_input} 的知识讲解，包括定义、原理、应用。
    如适用，可附带 Python 示例或保存文件辅助理解。
  agent: educator

# chat_task:
#   description: >
#     Use the conversation history to build your response to the user:

#     {history}

#     Respond to the user's message: {user_message}",
#   expected_output: >
#     Your output should be a relevant, accurate, and engaging response that directly addresses the user's query or continues the conversation logically.
#   agent: assistant





